// Regenerates fake/schema.gen.ts from packages/shared/src/db/database.types.ts.
//
//   node video/tools/capture/fake/gen-schema.mjs
//
// The fake backend needs two things the generated TypeScript types already
// know: every table's columns (so `select('*')` returns a complete row, with
// nulls where the seed said nothing) and the foreign keys (so an embedded
// select like `students(full_name)` resolves itself). Run it again after the
// DB types are regenerated. It reads a file; it never talks to a database.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const here = path.dirname(fileURLToPath(import.meta.url))
const src = path.resolve(here, '../../../../packages/shared/src/db/database.types.ts')
const lines = readFileSync(src, 'utf8').split(/\r?\n/)

// --- locate the `public` schema block -------------------------------------
const pubStart = lines.findIndex((l) => /^  public: \{$/.test(l))
if (pubStart < 0) throw new Error('public schema not found')
let pubEnd = pubStart + 1
while (pubEnd < lines.length && !/^  \}$/.test(lines[pubEnd])) pubEnd++

function section(name) {
  let s = -1
  for (let i = pubStart; i < pubEnd; i++) if (new RegExp(`^    ${name}: \\{$`).test(lines[i])) { s = i; break }
  if (s < 0) return [0, 0]
  let e = s + 1
  while (e < pubEnd && !/^    \}$/.test(lines[e])) e++
  return [s + 1, e]
}

// --- enums ------------------------------------------------------------------
const enums = {}
{
  const [s, e] = section('Enums')
  let cur = null
  let buf = ''
  const flush = () => {
    if (!cur) return
    enums[cur] = [...buf.matchAll(/"([^"]*)"/g)].map((m) => m[1])
    cur = null
    buf = ''
  }
  for (let i = s; i < e; i++) {
    const m = /^      (\w+):(.*)$/.exec(lines[i])
    if (m) {
      flush()
      cur = m[1]
      buf = m[2]
    } else if (cur) buf += lines[i]
  }
  flush()
}

// --- tables and views ---------------------------------------------------------
function kindOf(type) {
  const t = type.trim()
  const nullable = /\|\s*null\b/.test(t)
  const base = t.replace(/\|\s*null\b/g, '').trim()
  let kind = 'json'
  const en = /Database\["public"\]\["Enums"\]\["(\w+)"\]/.exec(base)
  if (en) kind = base.endsWith('[]') ? 'array' : `enum:${en[1]}`
  else if (base === 'string' || /^"/.test(base)) kind = 'string'
  else if (base === 'number') kind = 'number'
  else if (base === 'boolean') kind = 'boolean'
  else if (base.endsWith('[]')) kind = 'array'
  else if (base === 'Json') kind = 'json'
  else if (base === 'unknown') kind = 'json'
  return (nullable ? '?' : '') + kind
}

function parseRelations(s, e) {
  const out = []
  let i = s
  while (i < e) {
    if (/Relationships: \[\]/.test(lines[i])) return out
    if (/Relationships: \[$/.test(lines[i])) break
    i++
  }
  let cur = null
  for (; i < e; i++) {
    const l = lines[i]
    let m
    if ((m = /foreignKeyName: "([^"]+)"/.exec(l))) cur = { fk: m[1] }
    else if (cur && (m = /^\s*columns: \[([^\]]*)\]/.exec(l))) cur.cols = [...m[1].matchAll(/"([^"]+)"/g)].map((x) => x[1])
    else if (cur && (m = /isOneToOne: (true|false)/.exec(l))) cur.one = m[1] === 'true'
    else if (cur && (m = /referencedRelation: "([^"]+)"/.exec(l))) cur.to = m[1]
    else if (cur && (m = /referencedColumns: \[([^\]]*)\]/.exec(l))) {
      cur.toCols = [...m[1].matchAll(/"([^"]+)"/g)].map((x) => x[1])
      out.push(cur)
      cur = null
    }
  }
  return out
}

function parseRelationBlock(sectionName) {
  const [s, e] = section(sectionName)
  const out = {}
  let i = s
  while (i < e) {
    const m = /^      (\w+): \{$/.exec(lines[i])
    if (!m) { i++; continue }
    const name = m[1]
    let end = i + 1
    while (end < e && !/^      \}$/.test(lines[end])) end++
    // Row
    const cols = {}
    let r = i + 1
    while (r < end && !/^        Row: \{$/.test(lines[r])) r++
    r++
    let last = null
    for (; r < end && !/^        \}$/.test(lines[r]); r++) {
      const cm = /^          (\w+)\??: (.*)$/.exec(lines[r])
      if (cm) { last = cm[1]; cols[last] = cm[2] }
      else if (last) cols[last] += ' ' + lines[r].trim()
    }
    for (const k of Object.keys(cols)) cols[k] = kindOf(cols[k])
    out[name] = { cols, rels: parseRelations(i, end) }
    i = end + 1
  }
  return out
}

const tables = parseRelationBlock('Tables')
const views = parseRelationBlock('Views')

// --- functions (names only: used to tell "no handler yet" from "typo") ------
const functions = []
{
  const [s, e] = section('Functions')
  for (let i = s; i < e; i++) {
    const m = /^      (\w+): \{?/.exec(lines[i])
    if (m && !functions.includes(m[1])) functions.push(m[1])
  }
}

const body =
  `// GENERATED by gen-schema.mjs from packages/shared/src/db/database.types.ts.\n` +
  `// Do not edit. Column kinds: string | number | boolean | json | array | enum:<name>,\n` +
  `// prefixed with "?" when the column is nullable.\n\n` +
  `export type ColKind = string\n` +
  `export type Rel = { fk: string; cols: string[]; one: boolean; to: string; toCols: string[] }\n` +
  `export type TableSchema = { cols: Record<string, ColKind>; rels: Rel[] }\n\n` +
  `export const ENUMS: Record<string, string[]> = ${JSON.stringify(enums, null, 1)}\n\n` +
  `export const TABLES: Record<string, TableSchema> = ${JSON.stringify(tables)}\n\n` +
  `export const VIEWS: Record<string, TableSchema> = ${JSON.stringify(views)}\n\n` +
  `export const FUNCTIONS: string[] = ${JSON.stringify(functions)}\n`

writeFileSync(path.join(here, 'schema.gen.ts'), body)
console.log(`tables ${Object.keys(tables).length}, views ${Object.keys(views).length}, enums ${Object.keys(enums).length}, functions ${functions.length}`)

if (process.argv.includes('--print')) {
  for (const [name, t] of Object.entries({ ...tables, ...views })) {
    console.log(`\n${name}`)
    console.log('  ' + Object.entries(t.cols).map(([c, k]) => `${c}:${k}`).join('  '))
    for (const r of t.rels) console.log(`  -> ${r.to}(${r.toCols}) via ${r.cols} [${r.fk}]${r.one ? ' 1:1' : ''}`)
  }
}
